name: crome-logic

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - pygraphviz
  - spot
  - pre-commit
  - matplotlib
  - poetry
  - gcc
  - aenum
  - treelib
  - docker-py
  - dill
  - flask
  - pip
  - pip:
    - pyeda
    - bloom-filter